const PRODUCTS = [
  // ── Celadon (C) ──
  { code: "C-03",  name: "Smoke",           series: "C",   color: "#8A9090", price: 7.99, outOfStock: true  },
  { code: "C-05",  name: "Charcoal",        series: "C",   color: "#5A5A5A", price: 7.99 },
  { code: "C-19",  name: "Glacier",         series: "C",   color: "#B8D4D8", price: 7.99 },
  { code: "C-24",  name: "Succulent",       series: "C",   color: "#7BAE8C", price: 7.99 },
  { code: "C-25",  name: "Downpour",        series: "C",   color: "#6B9EC4", price: 7.99 },
  { code: "C-26",  name: "Lagoon",          series: "C",   color: "#4E9BAE", price: 7.99 },
  { code: "C-29",  name: "Deep Sea",        series: "C",   color: "#2A5F7A", price: 7.99 },
  { code: "C-32",  name: "Ochre",           series: "C",   color: "#C8963A", price: 7.99, outOfStock: true  },
  { code: "C-33",  name: "Sandalwood",      series: "C",   color: "#C4A882", price: 7.99 },
  { code: "C-42",  name: "Saguaro",         series: "C",   color: "#7DAB7A", price: 7.99 },
  { code: "C-52",  name: "Red Rock",        series: "C",   color: "#B04A36", price: 7.99 },
  { code: "C-54",  name: "Snapdragon",      series: "C",   color: "#E8884A", price: 7.99 },
  { code: "C-55",  name: "Poppy",           series: "C",   color: "#E05840", price: 7.99 },
  { code: "C-57",  name: "Mulberry",        series: "C",   color: "#7A4472", price: 7.99, outOfStock: true  },
  { code: "C-65",  name: "Tangelo",         series: "C",   color: "#E87A30", price: 7.99 },

  // ── Cosmos (CO) ──
  { code: "CO-03", name: "Event Horizon",   series: "CO",  color: "#1A1020", price: 8.99, isNew: true },
  { code: "CO-05", name: "Dark Matter",     series: "CO",  color: "#2A2035", price: 8.99, isNew: true },
  { code: "CO-06", name: "Supernova",       series: "CO",  color: "#8A3060", price: 8.99 },
  { code: "CO-21", name: "Galactic Glacier",series: "CO",  color: "#8AB8D0", price: 8.99, isNew: true },
  { code: "CO-24", name: "Blue Starlight",  series: "CO",  color: "#5070C0", price: 8.99, isNew: true },

  // ── Crawls (CR) ──
  { code: "CR-1",  name: "Black",           series: "CR",  color: "#1A1A1A", price: 7.99 },
  { code: "CR-12", name: "Speckled White",  series: "CR",  color: "#ECEAE5", price: 7.99 },
  { code: "CR-17", name: "Flux Crawl",      series: "CR",  color: "#D4C8B0", price: 7.99 },
  { code: "CR-18", name: "Speckled Flux Crawl", series: "CR", color: "#C8BEA5", price: 7.99 },
  { code: "CR-20", name: "Dark Blue",       series: "CR",  color: "#1E3A6A", price: 7.99 },
  { code: "CR-22", name: "Speckled Teal",   series: "CR",  color: "#4A8A8A", price: 7.99 },
  { code: "CR-41", name: "Lime",            series: "CR",  color: "#A0C840", price: 7.99 },
  { code: "CR-51", name: "Speckled Pink",   series: "CR",  color: "#E8A0A8", price: 7.99 },
  { code: "CR-54", name: "Purple",          series: "CR",  color: "#6A3A90", price: 7.99 },
  { code: "CR-58", name: "Red",             series: "CR",  color: "#B83020", price: 7.99 },
  { code: "CR-61", name: "Speckled Yellow", series: "CR",  color: "#E8D060", price: 7.99 },

  // ── Dipping & Layering (DL) ──
  { code: "DL-01", name: "Ebony",           series: "DL",  color: "#202020", price: 7.99 },
  { code: "DL-10", name: "Gloss Clear",     series: "DL",  color: "#D8EAF0", price: 7.99 },
  { code: "DL-11", name: "Enamel White",    series: "DL",  color: "#F2F0EC", price: 7.99 },
  { code: "DL-12", name: "Midnight Blue",   series: "DL",  color: "#1A2A50", price: 7.99 },
  { code: "DL-20", name: "Floating Blue",   series: "DL",  color: "#5880B8", price: 7.99 },
  { code: "DL-23", name: "Ultramarine",     series: "DL",  color: "#2040A0", price: 7.99 },
  { code: "DL-25", name: "Coastline",       series: "DL",  color: "#6899B4", price: 7.99 },
  { code: "DL-27", name: "Storm Cloud",     series: "DL",  color: "#7A8898", price: 7.99 },
  { code: "DL-33", name: "Low Tide",        series: "DL",  color: "#5A8888", price: 7.99 },
  { code: "DL-42", name: "River Moss",      series: "DL",  color: "#6A7A50", price: 7.99 },
  { code: "DL-57", name: "Mulberry Mist",   series: "DL",  color: "#9A6898", price: 7.99 },
  { code: "DL-59", name: "Brick Red",       series: "DL",  color: "#A03828", price: 7.99 },
  { code: "DL-60", name: "Honeycomb",       series: "DL",  color: "#D4A850", price: 7.99 },
  { code: "DL-63", name: "Stardust",        series: "DL",  color: "#A898C0", price: 7.99 },
  { code: "DL-70", name: "Oxblood",         series: "DL",  color: "#6A1818", price: 7.99 },

  // ── High Fire (HF) ──
  { code: "HF-09", name: "Zinc-Free Clear", series: "HF",  color: "#D0E8EE", price: 7.99 },
  { code: "HF-26", name: "Turquoise",       series: "HF",  color: "#30A8A0", price: 7.99 },
  { code: "HF-56", name: "Red Gloss",       series: "HF",  color: "#C02828", price: 7.99 },

  // ── Kiln Ice (KI) ──
  { code: "KI-11", name: "Snow Drift",      series: "KI",  color: "#EAF2F8", price: 8.49 },
  { code: "KI-18", name: "Arctic Blush",    series: "KI",  color: "#F0D8DC", price: 8.49 },
  { code: "KI-21", name: "Winter Glass",    series: "KI",  color: "#C8DCE8", price: 8.49 },
  { code: "KI-27", name: "Glacial Lake",    series: "KI",  color: "#70A8C8", price: 8.49 },
  { code: "KI-46", name: "Frozen Fern",     series: "KI",  color: "#88B898", price: 8.49 },
  { code: "KI-68", name: "Honey Crystal",   series: "KI",  color: "#D8A840", price: 8.49 },

  // ── Potter's Choice (PC) ──
  { code: "PC-09", name: "Vintage Gold",    series: "PC",  color: "#C0943A", price: 8.49 },
  { code: "PC-11", name: "Blue Spark",      series: "PC",  color: "#2858A8", price: 8.49 },
  { code: "PC-13", name: "Serpentine Green",series: "PC",  color: "#508858", price: 8.49 },
  { code: "PC-14", name: "Lapis Flow",      series: "PC",  color: "#384898", price: 8.49 },
  { code: "PC-15", name: "Satin Oribe",     series: "PC",  color: "#387848", price: 8.49 },
  { code: "PC-16", name: "Purple Crystal",  series: "PC",  color: "#684898", price: 8.49 },
  { code: "PC-17", name: "Honey Flux",      series: "PC",  color: "#C88840", price: 8.49 },
  { code: "PC-18", name: "Tuscan Blue",     series: "PC",  color: "#4068A0", price: 8.49 },
  { code: "PC-19", name: "Moon River",      series: "PC",  color: "#8898B8", price: 8.49 },
  { code: "PC-22", name: "Blue Stone",      series: "PC",  color: "#305880", price: 8.49 },
  { code: "PC-24", name: "Sapphire Float",  series: "PC",  color: "#1840A0", price: 8.49 },
  { code: "PC-26", name: "Blue Lagoon",     series: "PC",  color: "#3888A8", price: 8.49 },
  { code: "PC-38", name: "Iron Yellow",     series: "PC",  color: "#B89040", price: 8.49 },
  { code: "PC-44", name: "Sage",            series: "PC",  color: "#88A878", price: 8.49 },
  { code: "PC-47", name: "Emerald Falls",   series: "PC",  color: "#208858", price: 8.49 },
  { code: "PC-63", name: "Cosmic Tea Dust", series: "PC",  color: "#706858", price: 8.49 },
  { code: "PC-64", name: "Aventurine",      series: "PC",  color: "#386040", price: 8.49 },
  { code: "PC-65", name: "Black Aventurine",series: "PC",  color: "#202820", price: 8.49 },
  { code: "PC-66", name: "Cosmic Oilspot",  series: "PC",  color: "#281820", price: 8.49 },
  { code: "PC-67", name: "River Rock",      series: "PC",  color: "#786858", price: 8.49 },
  { code: "PC-68", name: "Golden Honey",    series: "PC",  color: "#C09030", price: 8.49 },
  { code: "PC-69", name: "Cosmic Gold Dust",series: "PC",  color: "#B09838", price: 8.49 },
  { code: "PC-70", name: "Copper Red",      series: "PC",  color: "#A83828", price: 8.49 },
  { code: "PC-71", name: "Flambe",          series: "PC",  color: "#C03030", price: 8.49 },
  { code: "PC-72", name: "Fire & Ice",      series: "PC",  color: "#A84858", price: 8.49 },

  // ── Potter's Choice Flux (PCF) ──
  { code: "PCF-03", name: "Midnight Run",   series: "PCF", color: "#181428", price: 8.49 },
  { code: "PCF-16", name: "Aurora Breeze",  series: "PCF", color: "#80B8C8", price: 8.49 },
  { code: "PCF-18", name: "Honeydew",       series: "PCF", color: "#A8D890", price: 8.49 },
  { code: "PCF-19", name: "Cirrus Flow",    series: "PCF", color: "#C8D8E8", price: 8.49 },
  { code: "PCF-21", name: "Ocean Drift",    series: "PCF", color: "#4888A8", price: 8.49 },
  { code: "PCF-33", name: "Mystic Tide",    series: "PCF", color: "#5060A0", price: 8.49 },
  { code: "PCF-36", name: "Rose Mist",      series: "PCF", color: "#D898A8", price: 8.49 },
  { code: "PCF-54", name: "Flux Blossom",   series: "PCF", color: "#C888A8", price: 8.49 },
  { code: "PCF-60", name: "Sunbeam",        series: "PCF", color: "#E8C840", price: 8.49 },
  { code: "PCF-63", name: "Sun Shower",     series: "PCF", color: "#E0B838", price: 8.49 },

  // ── Phase Glaze (PG) ──
  { code: "PG-24",  name: "Night Rain",     series: "PG",  color: "#283848", price: 8.49 },
];

const SERIES_NAMES = {
  C:   "Celadon",
  CO:  "Cosmos",
  CR:  "Crawls",
  DL:  "Dipping & Layering",
  HF:  "High Fire",
  KI:  "Kiln Ice",
  PC:  "Potter's Choice",
  PCF: "PC Flux",
  PG:  "Phase Glaze",
};
